# Generated by Django 4.2.15 on 2026-05-08 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DarijatDialect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم اللهجة")),
                (
                    "value",
                    models.CharField(
                        help_text="القيمة المضافة إلى style_instruction مثل: لهجة قطرية",
                        max_length=200,
                        verbose_name="القيمة",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="مميز (Premium)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "لهجة",
                "verbose_name_plural": "اللهجات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DarijatEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المشاعر")),
                (
                    "value",
                    models.CharField(
                        help_text="القيمة المضافة إلى style_instruction مثل: متحمس",
                        max_length=200,
                        verbose_name="القيمة",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="مميز (Premium)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "مشاعر",
                "verbose_name_plural": "المشاعر",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DarijatStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="اسم أسلوب الأداء"),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="القيمة المضافة إلى style_instruction مثل: معلق صوتي",
                        max_length=300,
                        verbose_name="القيمة",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="مميز (Premium)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "أسلوب أداء",
                "verbose_name_plural": "أساليب الأداء",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DarijatVoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الصوت")),
                (
                    "voice_name",
                    models.CharField(
                        help_text="القيمة المرسلة إلى واجهة داريجات (voice_name)",
                        max_length=100,
                        verbose_name="اسم الصوت في API",
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اللهجة / النبرة"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "ذكر"),
                            ("female", "انثى"),
                            ("children", "أطفال"),
                        ],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=True, verbose_name="مميز (Premium)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "demo_audio",
                    models.FileField(
                        blank=True,
                        help_text="MP3 demo file",
                        null=True,
                        upload_to="voice_demos/",
                        verbose_name="ملف العينة الصوتية",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "صوت داريجات",
                "verbose_name_plural": "أصوات داريجات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TTSProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("other", "Other Languages"),
                            ("arabic", "Arabic (Darijat)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(verbose_name="النص المدخل")),
                (
                    "voice_name",
                    models.CharField(max_length=100, verbose_name="اسم الصوت"),
                ),
                (
                    "style_instruction",
                    models.TextField(
                        blank=True, default="", verbose_name="تعليمات الأسلوب"
                    ),
                ),
                (
                    "openai_voice",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("openai_speed", models.FloatField(default=1.0)),
                ("openai_format", models.CharField(default="mp3", max_length=10)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result_file",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="مسار ملف النتيجة",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "char_count",
                    models.IntegerField(default=0, verbose_name="عدد الأحرف"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tts_processings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "معالجة تحويل نص إلى صوت",
                "verbose_name_plural": "معالجات تحويل نص إلى صوت",
                "db_table": "tts_processing",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="tts_process_user_id_86dde7_idx"
                    ),
                    models.Index(
                        fields=["processing_id"], name="tts_process_process_8d9f06_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tts_process_created_a5ba36_idx"
                    ),
                ],
            },
        ),
    ]
