# Generated by Django 4.2.15 on 2026-05-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_voice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiTTSConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_gemini_for_arabic",
                    models.BooleanField(
                        default=False,
                        help_text="عند التفعيل يتم توجيه طلبات العربية إلى Gemini TTS بدلاً من Darijat.",
                        verbose_name="استخدام Gemini بدلاً من Darijat",
                    ),
                ),
                (
                    "gemini_model",
                    models.CharField(
                        default="gemini-2.5-flash-preview-tts",
                        help_text="مثال: gemini-2.5-flash-preview-tts أو gemini-2.5-pro-preview-tts",
                        max_length=100,
                        verbose_name="نموذج Gemini",
                    ),
                ),
                (
                    "fallback_gemini_voice",
                    models.CharField(
                        default="Zephyr",
                        help_text="الصوت المستخدم عندما لا يكون للصوت المطلوب مقابل محدد في Gemini.",
                        max_length=100,
                        verbose_name="صوت Gemini الافتراضي",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة داخلية اختيارية (سبب التبديل، تاريخ البداية…).",
                        verbose_name="ملاحظة",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعداد Gemini TTS",
                "verbose_name_plural": "إعدادات Gemini TTS",
            },
        ),
        migrations.AddField(
            model_name="darijatvoice",
            name="gemini_voice",
            field=models.CharField(
                blank=True,
                default="",
                help_text="اسم الصوت في Gemini TTS المستخدم عند تفعيل Gemini كبديل. اتركه فارغاً لاستخدام الصوت الافتراضي من إعدادات GeminiTTSConfig. الأصوات المتاحة: Zephyr, Puck, Charon, Kore, Fenrir, Leda, Orus, Aoede, Callirrhoe, Autonoe, Enceladus, Iapetus, Umbriel, Algieba, Despina, Erinome, Algenib, Rasalgethi, Laomedeia, Achernar, Alnilam, Schedar, Gacrux, Pulcherrima, Achird, Zubenelgenubi, Vindemiatrix, Sadachbia, Sadaltager, Sulafat",
                max_length=100,
                verbose_name="صوت Gemini المقابل",
            ),
        ),
    ]
