# Generated by Django 4.2.15 on 2025-06-02 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processing_id", models.CharField(max_length=32, unique=True)),
                ("original_file", models.FileField(upload_to="temp_uploads/")),
                (
                    "result_file",
                    models.FileField(null=True, upload_to="processed_videos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("UPLOADING", "Uploading to GPU"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["processing_id"], name="v_bg_remove_process_5e5d9d_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="v_bg_remove_user_id_fce44c_idx",
                    ),
                ],
            },
        ),
    ]
