# Generated by Django 4.2.15 on 2025-06-02 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("v_bg_remover", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoprocessing",
            name="id",
        ),
        migrations.AlterField(
            model_name="videoprocessing",
            name="processing_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
