# Generated by Django 4.2.15 on 2025-06-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        ("v_bg_remover", "0002_remove_videoprocessing_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoprocessing",
            name="tool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tools.tool",
            ),
        ),
    ]
