build:
	docker compose -f local.yml up --build -d --remove-orphans

up:
	docker compose -f local.yml up -d

down:
	docker compose -f local.yml down

down-v:
	docker compose -f local.yml down -v

banker-config:
	docker compose -f local.yml config

makemigrations:
	docker compose -f local.yml run --rm api python manage.py makemigrations

migrate:
	docker compose -f local.yml run --rm api python manage.py migrate

collectstatic:
	docker compose -f local.yml run --rm api python manage.py collectstatic --no-input --clear

compilemessages:
	docker compose -f local.yml run --rm api python manage.py compilemessages --ignore=env

makemessages:
	docker compose -f local.yml run --rm api python manage.py makemessages -l ar -l en --ignore=env --no-obsolete

superuser:
	docker compose -f local.yml run --rm api python manage.py createsuperuser

flush:
	docker compose -f local.yml run --rm api python manage.py flush

network-inspect:
	docker network inspect banker_local_nw

banker-db:
	docker compose -f local.yml exec postgres psql --username=testuser --dbname=banker

backup:
	docker compose -f local.yml exec postgres backup.sh

showbackups:
	docker compose -f local.yml exec postgres backups.sh