# Generated by Django 4.2.15 on 2025-09-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
