# Generated by Django 4.2.15 on 2025-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_payment_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
