# Generated by Django 4.2.15 on 2025-08-03 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        ("plan_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantool",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantool_set",
                to="subscriptions.plan",
            ),
        ),
    ]
