# Generated by Django 4.2.15 on 2025-07-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartoonProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processing_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "prompt",
                    models.TextField(help_text="Text prompt for cartoon generation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to="cartoon_images/"
                    ),
                ),
                (
                    "result_file_data_id",
                    models.IntegerField(
                        blank=True, help_text="Reference to FileToolData ID", null=True
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.tool"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cartoon_processing",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="cartoon_pro_user_id_96d7ae_idx"
                    ),
                    models.Index(
                        fields=["processing_id"], name="cartoon_pro_process_da13eb_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="cartoon_pro_created_e73fdc_idx"
                    ),
                ],
            },
        ),
    ]
