# Generated by Django 4.2.15 on 2025-08-03 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("text_to_cartoon", "0001_initial"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartoonprocessing",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tools.tool"
            ),
        ),
    ]
