# Generated by Django 4.2.15 on 2025-08-03 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("text_to_cartoon", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartoonprocessing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="cartoonprocessing",
            index=models.Index(
                fields=["user", "status"], name="cartoon_pro_user_id_96d7ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartoonprocessing",
            index=models.Index(
                fields=["processing_id"], name="cartoon_pro_process_da13eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartoonprocessing",
            index=models.Index(
                fields=["created_at"], name="cartoon_pro_created_e73fdc_idx"
            ),
        ),
    ]
