# Generated by Django 4.2.15 on 2025-07-25 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCaptionProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processing_id", models.UUIDField(db_index=True, unique=True)),
                ("original_file", models.FileField(upload_to="temp_caption_uploads/")),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to="processed_captioned_videos/"
                    ),
                ),
                ("target_language", models.CharField(default="en", max_length=10)),
                ("font_family", models.CharField(default="Arial.ttf", max_length=100)),
                ("font_size", models.IntegerField(default=24)),
                ("font_color", models.CharField(default="white", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("UPLOADING", "Uploading"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "video_duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.tool"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="video_capti_user_id_84dfea_idx"
                    ),
                    models.Index(
                        fields=["processing_id"], name="video_capti_process_887995_idx"
                    ),
                ],
            },
        ),
    ]
