# Generated by Django 4.2.15 on 2025-07-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processing_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "original_file",
                    models.FileField(
                        blank=True, null=True, upload_to="temp_audio_uploads/"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                            ("ru", "Russian"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("zh", "Chinese"),
                            ("ar", "Arabic"),
                            ("hi", "Hindi"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("UPLOADING", "Uploading"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("result_text", models.TextField(blank=True, null=True)),
                (
                    "result_text_id",
                    models.IntegerField(
                        blank=True, help_text="Reference to TextToolData ID", null=True
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.tool"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_processing",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="voice_proce_user_id_002493_idx"
                    ),
                    models.Index(
                        fields=["processing_id"], name="voice_proce_process_e66a60_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="voice_proce_created_ed211e_idx"
                    ),
                ],
            },
        ),
    ]
