# Generated by Django 4.2.15 on 2025-10-02 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tool_data", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filetooldata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
