# Generated by Django 4.2.15 on 2025-10-02 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tool_data", "0003_filetooldata_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filetooldata",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
