# Generated by Django 4.2.15 on 2025-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
