# Generated by Django 4.2.15 on 2025-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
