# Generated by Django 4.2.15 on 2025-10-02 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0005_phonenumber_terms_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="terms_accepted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
