# Generated by Django 4.2.15 on 2025-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0006_alter_phonenumber_terms_accepted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
